name: Auto deploy to qcloud cos

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to qcloud by sftp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          password: ${{ secrets.PASSWORD }} #引用之前创建好的secret
          remote_path: '/'
